### ISSUE TITLE
Asserting error thrown no longer works as of 2.11.3

### ISSUE THREAD

**Issue by jasonmit** [emberjs/ember-mocha#141]
Unsure where the proper fix belongs, but I believe it surfaced as part of:
https://github.com/emberjs/ember.js/pull/14898

Example of test that now fails since the assertion is not handled by mocha/chai before the error is thrown:

```js
it('x-foo throws on initialization if no model is provided', function() {
  expect(() => {
    this.render(hbs`{{x-foo}}`);
  }).to.throw('model attribute must be provided to x-foo');
});
```

**Comment by Turbo87** [comment]
@workmanw @rwjblue any comments?

**Comment by Turbo87** [comment]
okay, so I got several opinions on this:

- `expect().to.throw()` is provided by Chai and https://github.com/ember-cli/ember-cli-chai, so if that was broken the issue should be fixed over there
- `expect().to.throw()` is not broken since it works very well when you put e.g. `throw new Error('foo')` inside of it
- if `this.render()` threw previously, but is not throwing anymore then that is an API change of Ember itself

**Comment by Turbo87** [comment]
this seems to be an issue in Ember itself, so I'll close the issue here for now in favor of https://github.com/emberjs/ember.js/issues/15013
