### ISSUE TITLE
Anything blocking deploying the new testing API?

### ISSUE THREAD

**Issue by ejlangev** [emberjs/ember-mocha#205]
Was a bit confused because the examples in the docs and the migration guide do not seem to run properly in a new ember app.  It appears that there needs to be a new release for the new API which is currently in beta.  Is there some place that tracks the status to shipping the new version?

**Comment by Turbo87** [comment]
> Anything blocking deploying the new testing API?

free time 😞 

> Was a bit confused because the examples in the docs and the migration guide do not seem to run properly in a new ember app.

they do run properly, but what you see at https://github.com/emberjs/ember-mocha/ is the docs for the master branch. you should look at the docs corresponding to the version that you use, e.g. https://github.com/emberjs/ember-mocha/tree/v0.13.1

> Is there some place that tracks the status to shipping the new version?

this issue here, I guess 😉

**Comment by ejlangev** [comment]
> free time 😞

Well if there's anything I can do to help let me know.

**Comment by jgwhite** [comment]
@Turbo87 what’s the recommended way to test the beta release? Is there a complementary release of [ember-cli-mocha](https://github.com/ember-cli/ember-cli-mocha/releases) we can use? Or is it recommended to add `ember-mocha` as a direct dependency?

**Comment by jimenglish81** [comment]
I was just checking out the tests on `master` and noticed it seems to not play well with `ember/test-helpers ^0.7.21`
It looks to me like because of the shared context in `Mocha` (https://github.com/mochajs/mocha/wiki/Shared-Behaviours) the extra keys added have to be deleted after each test https://github.com/emberjs/ember-mocha/blob/master/addon-test-support/ember-mocha/setup-test.js#L45

However post `0.7.21` ember test helpers now uses `definedProperty` which isn't `enumerable` or `configurable` by default, so doesn't get deleted. Next time `setupTest` is called the properties error when being defined as they are not `writeable`.
(`Cannot redefine property: owner`)

An "easy" fix looks like adding `enumerable` and `configurable` to the descriptor in `ember/test-helpers`; this might not be desirable though. I am happy to help out if there are any suggestions?

**Comment by Turbo87** [comment]
@jimenglish81 good point, thanks for the analysis. @rwjblue any suggestions? 🤔

**Comment by rwjblue** [comment]
> An "easy" fix looks like adding enumerable and configurable to the descriptor in ember/test-helpers; this might not be desirable though.

This seems like the right path forward to me...

**Comment by jimenglish81** [comment]
@rwjblue great thanks for your feedback. I have created a PR...
https://github.com/emberjs/ember-test-helpers/pull/374

**Comment by jimenglish81** [comment]
> add a codemod to https://github.com/Turbo87/ember-mocha-codemods that migrates to the new APIs

@Turbo87 can I help with this at all?

**Comment by Turbo87** [comment]
@jimenglish81 you should talk to @jgwhite. he wanted to look into the codemod situation :)

**Comment by jgwhite** [comment]
@Turbo87 @jimenglish81 haha, yes although I must admit I’ve been dragging my heels. 😅

I’ve proposed a little plan of attack to the team at Heroku but we’ve yet to schedule it in.

@jimenglish81 if you want to dive in, don’t let me stop you!

**Comment by rwjblue** [comment]
Looks like @rondale-sc picked this up a bit and has a good start going over in https://github.com/Turbo87/ember-mocha-codemods/pull/17.

**Comment by rondale-sc** [comment]
The codemod has been merged into ember-mocha-codemods repo and is in need of some testing.  But I think we may be able to start pushing this beta forward now?

**Comment by Turbo87** [comment]
@rondale-sc I agree. I will release this as stable next week.

**Comment by jgwhite** [comment]
Fabulous work, kudos @turbo87 and @rondale-sc. Can’t wait to migrate our test suite.

**Comment by Turbo87** [comment]
released as v0.14.0
