### ISSUE TITLE
cannot run tests with ember@3.3.1

### ISSUE THREAD

**Issue by efx** [emberjs/ember-mocha#214]
I have just tried upgrading our application to the latest ember version and received these errors when running `ember test --server`. Do let me know if I should file this in ember.js.
```
$ npm ls ember-mocha

└─┬ ember-cli-mocha@0.15.0
  └── ember-mocha@0.13.1
$ npm ls ember-source
└── ember-source@3.3.1
```
<img width="1438" alt="screen shot 2018-08-07 at 17 12 29" src="https://user-images.githubusercontent.com/472721/43802958-61c4e7e4-9a65-11e8-89dc-73d1116d14a8.png">
This seems to lead to further errors:
<img width="825" alt="screen shot 2018-08-07 at 17 15 22" src="https://user-images.githubusercontent.com/472721/43803004-81ed0dee-9a65-11e8-9ce3-c9e4caea1c38.png">

**Comment by yads** [comment]
Seems to be due to the global-resolver in ember expecting a props object in Ember 3.3
https://github.com/emberjs/ember.js/blob/v3.3.2/packages/%40ember/application/globals-resolver.js#L85

I fixed this in my branch by changing the tests/helpers/resolver.js file that's generated from here https://github.com/ember-cli/ember-cli-mocha/blob/v0.14.5/blueprints/ember-cli-mocha/files/tests/helpers/resolver.js

to this

```
import Resolver from '../../resolver';
import config from '../../config/environment';

const resolver = Resolver.create({
  namespace: {
    modulePrefix: config.modulePrefix,
    podModulePrefix: config.podModulePrefix
  }
});

export default resolver;
```

**Comment by efx** [comment]
Closing as I have moved our app to recent ember-source and things worked fine.
